"""empty message

Revision ID: 69884bcfdfc8
Revises: 29b662f71906
Create Date: 2024-09-18 01:30:48.861862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69884bcfdfc8'
down_revision = '29b662f71906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_color', sa.String(length=20), nullable=True))
        batch_op.drop_column('passcolor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passcolor', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('pass_color')

    # ### end Alembic commands ###
