"""empty message

Revision ID: a95d04a9a945
Revises: 69884bcfdfc8
Create Date: 2024-09-18 13:15:09.173497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95d04a9a945'
down_revision = '69884bcfdfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_auth_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_auth_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_auth_complete')
        batch_op.drop_column('color_auth_complete')

    # ### end Alembic commands ###
